server:
  port: 8084
dubbo:
  # 配置服务信息
  application:
    name: dubbo-consumer
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://localhost:8848?namespace=bf0ad9fa-6bfb-4085-8c64-c01669bdd4bd&register-consumer-url=true
  # 设置超时时间
  consumer:
    timeout: 4000
  protocol:
    name: dubbo
    port: -1
spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
